from enum import Enum


class ExamTypes(Enum):
    NONE="brak"
    HAEMOGLOBIN = "Hemoglobina"
    LEUKOCYTES = "Leukocyty"
    PLATELETS = "Płytki krwi"
    HAEMATOCRIT = "Hematokryt"
    INR = "INR"
    SODIUM = "Sód"
    POTASSIUM = "Potas"
    CHLORIDE = "Chlorek"
    UREA_NITROGEN = "Azot mocznikowy"
    OSMOLALITY_SERUM = "Osmolalność surowicy"
    GLUCOSE = "Glukoza"
    HbA1c = "HbA1c"
    URIBILINOGEN = "Urobilinogen"
    BILIRUBIN = "Bilirubina"
    KETONE = "Ketony"
    BLOOD = "Krew"
    PROTEIN = "Białko"
    PH = "pH"
    GRASS = "Trawa"
    BIRCH_TREE = "Brzoza"
    WORMWOOD = "Bylica"
    CAT = "Kot"
    DOG = "Pies"
    CLADOSPORIUM = "Cladosporium herbarum"
    ALTERNARIA = "Alternaria alternata"
    EGG_WHITE = "Białko jaja"
    EGG_YOLK = "Żółtko jaja"
    MILK = "Mleko"
    COD = "Dorsz"
    CASEIN = "Kazeina"
    WHEAT_FLOUR = "Mąka pszenna"
    RICE = "Ryż"
    SOY = "Soja"
    PEANUT = "Orzech ziemny"
    HAZELNUT = "Orzech laskowy"
    CARROT = "Marchewka"
    POTATO = "Ziemniak"
    APPLE = "Jabłko"
